language: cpp

compiler:
  - gcc
  - clang

env:
  - ANALYZE=false
  - ANALYZE=true

before_install:
  - chmod +x ./tools/travis/linux/travis.sh
  - chmod +x ./tools/travis/linux/build.sh

install:
  # only install clang/cppcheck if necessary
  - if [ "$CXX" = "clang++" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; sudo apt-get -qq update; sudo apt-get install clang; fi
  - if [ $ANALYZE = "true" ] && [ "$CXX" = "g++" ]; then sudo apt-get install -qq cppcheck; fi

script:
  - ./tools/travis/linux/travis.sh

notifications:
  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "irc.freenode.org#rigsofrods-dev"
    use_notice: true
    skip_join: true
